name: Hexo Publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Blog Branche
        uses: actions/checkout@v2
        with: 
          ref: Blog
      - name: Set Git Config
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name 'jiayaoO3O'
          git config --global user.email 'jiayao3.14@outlook.com'
      - name: Install Node.js 12 and Hexo
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - name: Install Pandoc
        run: |
          wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-linux-amd64.tar.gz
          tar xvzf ./*.tar.gz
          export PATH="$PATH:./pandoc-2.13/bin"
          pandoc --help
      - run: |
          rm -rf /home/runner/work/jiayaoO3O.github.io/jiayaoO3O.github.io/node_modules
          ls
          npm install hexo-cli -g
          npm install
          hexo version
      - name: Deploy Hexo
        env:
          TZ: Asia/Shanghai
        run: |
          hexo clean
          hexo g -d